apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
      - name: app
        image: cbron/multiappdemo-frontend:latest
        imagePullPolicy: Always
        env:
        - name: BACKEND
          value: "http://backend-svc:8081" # could also use existing env vars from k8s
        ports:
        - containerPort: 8080
