apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - name: app
        image: cbron/multiappdemo-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
